# what is numpy?
Numpy is the fundamental package for scientific computing in python.It is a python library that provides a multidimensional array object,various derived objects(such as masked arrays and matrices),and an assortment of routines for fast operations on arrays,including mathematical,logical ,shape manipulation,sorting,selecting,I/O,discreate fourier transforms,basic linear algebra,basic statistical operations,random simulation and much more.
At the core of numpy package,is the ndarray object.This encapsulates n-dimensional arrays of homogeneous data types

# Numpy array vs python sequances
.Numpy arrays have a fixed size at creation,unlike python lists(which can grow dynamically).Changing the size of the ndarray will create a new array and delete the original.
. The elements in a numpy array are all required to be of the same data type,and thus will be the same size in memory.
. Numpy arrays facilitates advanced mathematical and other types of operations on large number of data .Typically,such operations are executed more efficently and with less code than is possible using python's builtin sequances.
.A growing plethora of scientific and mathematical python -based packages are using Numpy arrays:though these typically support python-sequances input,they convert such input to numpy arrays prior to processing,and they often output Numpy arrays.

# creating numpy arrays

In [4]:
# np.array
import numpy as np
arr =np.array([1,2,3,4])  #1D
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [5]:
# 2D and 3D
arr = np.array([[1,2,3],[4,5,6]])
print(arr,type(arr))

[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'>


In [6]:
c = np.array([[[1,2],[3,4],[5,6]]])
print(c,type(c))

[[[1 2]
  [3 4]
  [5 6]]] <class 'numpy.ndarray'>


In [43]:
# dtype
np.array([1,2,3],dtype = float)

array([1., 2., 3.])

In [44]:
np.array([1,2,3],dtype = bool)

array([ True,  True,  True])

In [45]:
# np.arange
np.arange(1,10,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [46]:
# With reshape
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [47]:
# np.ones
np.ones(4)

array([1., 1., 1., 1.])

In [48]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [50]:
# np.zeors
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [51]:
# np.random
np.random.randint(1,10,(5,5))

array([[8, 4, 6, 2, 3],
       [3, 7, 3, 2, 1],
       [4, 5, 5, 6, 9],
       [3, 6, 6, 9, 4],
       [5, 1, 9, 1, 3]])

In [52]:
np.random.rand(29)

array([0.96773847, 0.96437415, 0.19543344, 0.77998726, 0.50117571,
       0.87699628, 0.81707346, 0.79135757, 0.23465935, 0.09032071,
       0.80007036, 0.94687567, 0.57235418, 0.0589123 , 0.79012207,
       0.74787576, 0.3160241 , 0.27475065, 0.70327288, 0.97766686,
       0.88038361, 0.44008703, 0.75238716, 0.44462058, 0.19087757,
       0.9952446 , 0.89473226, 0.32986585, 0.27019475])

In [53]:
np.random.randint(1,20,(5,5))

array([[13,  4, 18, 14,  6],
       [ 6, 11,  7, 16, 15],
       [ 3, 11, 13, 15,  3],
       [16, 15, 12,  1, 16],
       [17,  5, 19, 15,  5]])

In [54]:
# np.linspace
np.linspace(1,20,10)

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [55]:
# np.identity
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [56]:
# np.eye
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [57]:
# np.empty
np.empty((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# Array attributes

In [34]:
a1 = np.arange(10)
a2 = np.arange(12,dtype = float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

# Ndim   Number of dimesions

In [36]:
a1.ndim

1

In [37]:
print(a2.ndim)
print(a3.ndim)

2
3


# shape tells us about the shape

In [38]:
print(a1.shape)
print(a2.shape)
print(a3.shape)

(10,)
(3, 4)
(2, 2, 2)


# size tells us about number of items

In [39]:
print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


# itemsize size occupied by each item

In [40]:
print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

4
8
4


# dtype data type of each array

In [42]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


# changing datatype

In [62]:
# astype

a2.astype(np.int8)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int8)

# Array operations

In [66]:
a4 = np.arange(12).reshape(3,4)
a5= np.arange(12,24).reshape(3,4)

In [67]:
# scaler operations
# arithmetic
a4 + 1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [68]:
a5 *2

array([[24, 26, 28, 30],
       [32, 34, 36, 38],
       [40, 42, 44, 46]])

In [73]:
# relational
a4 >a5

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [74]:
a4 < a5

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [75]:
# vector operaitons
a4 + a5

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [76]:
a4 * a5

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

# Array functions

In [77]:
a1 = np.random.random((3,3))
a2 = np.round(a1 * 100)
a1

array([[0.27506174, 0.64966498, 0.02797562],
       [0.10400207, 0.22585864, 0.37522796],
       [0.57723587, 0.08414077, 0.16511072]])

In [78]:
a2

array([[28., 65.,  3.],
       [10., 23., 38.],
       [58.,  8., 17.]])

In [83]:
# min/max/sum/prod
# column wise
print(a1.max())
print(np.min(a1))
print(np.sum(a1))
print(np.prod(a1))

0.6496649844316182
0.027975620302706394
2.4842783681677227
3.5335260969907367e-07


In [87]:
# row wise
print(np.max(a1,axis = 1))
print(np.min(a1,axis = 1))
print(np.sum(a1,axis = 1))

[0.64966498 0.37522796 0.57723587]
[0.02797562 0.10400207 0.08414077]
[0.95270234 0.70508867 0.82648736]


In [88]:
# mean/median/std/var

print(np.mean(a1))
print(np.median(a1))
print(np.std(a1))
print(np.var(a1))
print()
print()


# row wise
print(np.mean(a1,axis = 1))
print(np.median(a1,axis = 1))
print(np.std(a1,axis = 1))
print(np.var(a1,axis = 1))

0.27603092979641364
0.2258586446991424
0.2062726251498313
0.04254839588620282


[0.31756745 0.23502956 0.27549579]
[0.27506174 0.22585864 0.16511072]
[0.25557708 0.11091724 0.21590791]
[0.06531965 0.01230263 0.04661623]


In [91]:
# trigonometric functions
print(np.sin(a1))
print(np.cos(a1))

[[0.27160636 0.60491967 0.02797197]
 [0.10381468 0.22394328 0.36648464]
 [0.54570975 0.08404152 0.16436154]]
[[0.96240843 0.7962865  0.99960871]
 [0.99459666 0.97460218 0.9304241 ]
 [0.83797426 0.99646225 0.98640016]]


In [94]:
# dot product 
# this can happen only when row of one array is equal to the column of another array then in that case we can do dot multiplication
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [96]:
# log and exponents
print(np.log(a1))
print(np.exp(a1))

[[-1.2907597  -0.43129846 -3.57642185]
 [-2.26334451 -1.48784594 -0.98022155]
 [-0.54950431 -2.47526403 -1.80113902]]
[[1.31661196 1.9148992  1.02837061]
 [1.10960275 1.25339848 1.45532313]
 [1.7811084  1.08778201 1.1795237 ]]


In [101]:
# round/floor /ceil
print(np.round(np.random.random((2,3))*100))
print()
print(np.floor(np.random.random((2,3))*100))
print()
print(np.ceil(np.random.random((2,3))*100))

[[66. 41. 33.]
 [56. 82. 64.]]

[[93. 31. 46.]
 [50. 70. 15.]]

[[ 29.   3. 100.]
 [  1.  32.  59.]]


# indexing and slicing

In [102]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [103]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [104]:
a1[-1]

9

In [105]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [110]:
a2[1,2]

6

In [111]:
a2[2,3]

11

In [112]:
a2[1,0]

4

In [113]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [114]:
a3[1,0,1]

5

In [115]:
a3[1,1,0]

6

In [116]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [118]:
a1[2:5]

array([2, 3, 4])

In [119]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [120]:
a2[1,1:3]

array([5, 6])

In [121]:
a2[0]

array([0, 1, 2, 3])

In [122]:
a2[:,2]

array([ 2,  6, 10])

In [126]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [129]:
a2[0::2,0::3]

array([[ 0,  3],
       [ 8, 11]])

# iterating

In [130]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [134]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [135]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [136]:
for i in np.nditer(a2):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [137]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [138]:
for i in range(len(a2)):
    print(a2[i])

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


# Reshaping, Transpose,Ravel

In [139]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [140]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [142]:
np.transpose(a3)

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [145]:
np.ravel(a2)  # representing high dimension data in 1D 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [146]:
np.ravel(a3)

array([0, 1, 2, 3, 4, 5, 6, 7])

# stacking

In [150]:
# horizontal stacking
a3 = np.arange(12).reshape(3,4)
a4 = np.arange(12,24).reshape(3,4)
np.hstack((a3,a4))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [151]:
# vertical stacking
np.vstack((a3,a4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# splitting

In [158]:
# horizontal split
np.hsplit(a3,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [160]:
# vertical splitting 
np.vsplit(a4,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]