In [1]:
import numpy as np 

In [8]:
 # np.sort
# code
a = np.random.randint(1,100,15)
print(a)
print()
print(np.sort(a))

[96 96 61 95 16  6 98 28 74 24 25 45 38 99  9]

[ 6  9 16 24 25 28 38 45 61 74 95 96 96 98 99]


In [9]:
b = np.random.randint(1,100,24).reshape(6,4)
print(b)
print()
print(np.sort(b))

[[47 54 46 36]
 [66 84 30 89]
 [85 99 76 70]
 [31 57 92 50]
 [ 9 78 86 13]
 [49 44 76 15]]

[[36 46 47 54]
 [30 66 84 89]
 [70 76 85 99]
 [31 50 57 92]
 [ 9 13 78 86]
 [15 44 49 76]]


In [10]:
# np.append
print(np.append(a,100))
print(np.append(b,np.ones((b.shape[0],1)),axis = 1))

[ 96  96  61  95  16   6  98  28  74  24  25  45  38  99   9 100]
[[47. 54. 46. 36.  1.]
 [66. 84. 30. 89.  1.]
 [85. 99. 76. 70.  1.]
 [31. 57. 92. 50.  1.]
 [ 9. 78. 86. 13.  1.]
 [49. 44. 76. 15.  1.]]


In [29]:
# np.concatenate
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)
print(c)
print(d)

print()
print(np.concatenate((c,d),axis=1))
print()
print(np.concatenate((c,d),axis=0))

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]

[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [30]:
# np.unique
# with the help of np.unique()method,we can get the unique values from an array gives as parameter in np.unique() method.
# code
e = np.array([1,1,2,3,4,3,2,1,23,4,54,6,7,88])
f = np.array([[1,2,3,1],[1,2,3,2]])
print(e)
print(f)
print()

print(np.unique(e))
print(np.unique(f))

[ 1  1  2  3  4  3  2  1 23  4 54  6  7 88]
[[1 2 3 1]
 [1 2 3 2]]

[ 1  2  3  4  6  7 23 54 88]
[1 2 3]


In [31]:
# np.expand_dims
# with help of numpy . expand_dims() method we ca nget the expanded dimensions of an array
a

array([110, 530,  61,  95,  16,   6,  98,  28,  74,  24,  25,  45,  38,
        99,   9])

In [32]:
print(np.expand_dims(a,axis = 0))
print(np.expand_dims(a,axis = 1))

[[110 530  61  95  16   6  98  28  74  24  25  45  38  99   9]]
[[110]
 [530]
 [ 61]
 [ 95]
 [ 16]
 [  6]
 [ 98]
 [ 28]
 [ 74]
 [ 24]
 [ 25]
 [ 45]
 [ 38]
 [ 99]
 [  9]]


In [33]:
# NP.WHERE
# THE NUMPY .WHERE() FUNCTION RETURNS THE INDICES OF ELEMENTS IN AN INPUT ARRAY WHERE THE GIVEN CONDITION IS SATISFIED
print(a)
print(np.where(a > 50))
print(np.where(a<50))
print(np.where(a == 0))
# Another way
# replace all values > 50 with 0
# print(np.where(condition,True,False))
print(np.where(a > 50 , 0,a))
print()
print(np.where(a % 2 == 0 ,0,a))

[110 530  61  95  16   6  98  28  74  24  25  45  38  99   9]
(array([ 0,  1,  2,  3,  6,  8, 13], dtype=int64),)
(array([ 4,  5,  7,  9, 10, 11, 12, 14], dtype=int64),)
(array([], dtype=int64),)
[ 0  0  0  0 16  6  0 28  0 24 25 45 38  0  9]

[ 0  0 61 95  0  0  0  0  0  0 25 45  0 99  9]


In [34]:
# np.argmax
# the numpy .argmanx() function returns indices of the max element of the array in a particular axis
print(np.argmax(a))
print(a)
print(np.argmax(b,axis = 0))
print()
print(b)
print()
print(np.argmax(b,axis = 1))

1
[110 530  61  95  16   6  98  28  74  24  25  45  38  99   9]
[2 2 3 1]

[[47 54 46 36]
 [66 84 30 89]
 [85 99 76 70]
 [31 57 92 50]
 [ 9 78 86 13]
 [49 44 76 15]]

[1 3 1 2 2 2]


In [35]:
# np.argmin
print(np.argmin(a))
print()
print(np.argmin(b,axis = 1))
print(np.argmin(b,axis = 0))

5

[3 2 3 0 0 3]
[4 5 1 4]


In [18]:
# np.cumsum
# numpy.cumsum() function is used when we wnat to compute the cumulative sum of arrays over a given axis
print(np.cumsum(a))
print()
print(np.cumsum(b,axis = 1))
print()
print(np.cumsum(b ,axis = 0))

[ 96 192 253 348 364 370 468 496 570 594 619 664 702 801 810]

[[ 47 101 147 183]
 [ 66 150 180 269]
 [ 85 184 260 330]
 [ 31  88 180 230]
 [  9  87 173 186]
 [ 49  93 169 184]]

[[ 47  54  46  36]
 [113 138  76 125]
 [198 237 152 195]
 [229 294 244 245]
 [238 372 330 258]
 [287 416 406 273]]


In [19]:
# np.cumprod
print(np.cumprod(a))
print()
print(np.cumprod(b,axis = 1))
print()
print(np.cumprod(b,axis = 0))


[         96        9216      562176    53406720   854507520   832077824
   -60751872 -1701052416 -1323827200 -1707081728   272629760  -616562688
 -1954545664  -226492416 -2038431744]

[[      47     2538   116748  4202928]
 [      66     5544   166320 14802480]
 [      85     8415   639540 44767800]
 [      31     1767   162564  8128200]
 [       9      702    60372   784836]
 [      49     2156   163856  2457840]]

[[         47          54          46          36]
 [       3102        4536        1380        3204]
 [     263670      449064      104880      224280]
 [    8173770    25596648     9648960    11214000]
 [   73563930  1996538544   829810560   145782000]
 [ -690334726  1948350016 -1358906880 -2108237296]]


In [20]:
# np.percentile
# numpy.percentile() function used to compute the nth percentile of the given data(array elements) along the specified axis
print(np.percentile(a,100))

99.0


In [21]:
print(np.median(a))
print(np.median(b,axis = 1))
print(np.median(b,axis = 0))

45.0
[46.5 75.  80.5 53.5 45.5 46.5]
[48.  67.5 76.  43. ]


In [36]:
# np.histogram
# Numpy has a built in numpy histogram() function which represents the frequancy of data distribution in the graphical form.
# cdoe
print(np.histogram(a,bins = [10,20,30,40,50,60,70,80]))
print()


(array([1, 3, 1, 1, 0, 1, 1], dtype=int64), array([10, 20, 30, 40, 50, 60, 70, 80]))



In [37]:
# np.corecoef
# Return pearson product moment correlation coefficients
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])
print(np.corrcoef(salary,experience))

[[1.         0.25344572]
 [0.25344572 1.        ]]


In [38]:
# np.sin
# with the help of numpy.isin() method,we can see that one array having values are checked in a different numpy array
# having differnet elements with different sizes.
item = [10,20,30,40,50,60,70,80]
a[np.isin(a,item)]

array([], dtype=int32)

In [39]:
# np.flip
# the numpy.flip() function reverses the order of array elements along the specified axis ,preserving the shape of array
print(np.flip(a))
print()
print(np.flip(b))
print()
print(np.flip(b,axis = 1))
print()
print(np.flip(b,axis = 0))

[  9  99  38  45  25  24  74  28  98   6  16  95  61 530 110]

[[15 76 44 49]
 [13 86 78  9]
 [50 92 57 31]
 [70 76 99 85]
 [89 30 84 66]
 [36 46 54 47]]

[[36 46 54 47]
 [89 30 84 66]
 [70 76 99 85]
 [50 92 57 31]
 [13 86 78  9]
 [15 76 44 49]]

[[49 44 76 15]
 [ 9 78 86 13]
 [31 57 92 50]
 [85 99 76 70]
 [66 84 30 89]
 [47 54 46 36]]


In [40]:
# np.put
# the numpy.put function replaces specific elements of an array with given vlaues of p_array . array indexed works on flattened array.
print(a)
np.put(a,[0,1],[110,530])
print(a)

[110 530  61  95  16   6  98  28  74  24  25  45  38  99   9]
[110 530  61  95  16   6  98  28  74  24  25  45  38  99   9]


In [41]:
# np.delete
#the numpy.delete()funciton returns a new array with the deletion of sub_arrays along with the mentioned axis.
print(a)
print(np.delete(a,0))
print(np.delete(a,[1,2,4]))

[110 530  61  95  16   6  98  28  74  24  25  45  38  99   9]
[530  61  95  16   6  98  28  74  24  25  45  38  99   9]
[110  95   6  98  28  74  24  25  45  38  99   9]


# set functions
. np.union1d

.np.intersect1d

.np.setdeff1d


.np.setxor1d


..np.in1d

In [47]:
m = np.array([1,2,3,4,5])
n = np.array([5,6,7,8,9,2])
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
np.intersect1d(m,n)

array([2, 5])

In [49]:
np.setdiff1d(m,n)

array([1, 3, 4])

In [50]:
np.setxor1d(m,n)

array([1, 3, 4, 6, 7, 8, 9])

In [54]:
m[np.in1d(m,1)]

array([1])

In [56]:
np.clip(a,25,75)

array([75, 75, 61, 75, 25, 25, 75, 28, 74, 25, 25, 45, 38, 75, 25])